# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ag/orbit/gui/qt/wallet/create.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewWallet(object):
    def setupUi(self, NewWallet):
        NewWallet.setObjectName("NewWallet")
        NewWallet.resize(524, 407)
        NewWallet.setSizeGripEnabled(True)
        NewWallet.setModal(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(NewWallet)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancelButton = QtWidgets.QPushButton(NewWallet)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(NewWallet)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.name = QtWidgets.QLineEdit(NewWallet)
        self.name.setObjectName("name")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.groupBox = QtWidgets.QGroupBox(NewWallet)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.password = QtWidgets.QLineEdit(self.groupBox)
        self.password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.password)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.passwordVerify = QtWidgets.QLineEdit(self.groupBox)
        self.passwordVerify.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.passwordVerify.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordVerify.setObjectName("passwordVerify")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordVerify)
        self.verticalLayout.addLayout(self.formLayout)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.error = QtWidgets.QLabel(NewWallet)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.error.setFont(font)
        self.error.setStyleSheet("color:red")
        self.error.setAlignment(QtCore.Qt.AlignCenter)
        self.error.setWordWrap(True)
        self.error.setObjectName("error")
        self.verticalLayout_2.addWidget(self.error)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.saveButton = QtWidgets.QPushButton(NewWallet)
        self.saveButton.setDefault(True)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(NewWallet)
        QtCore.QMetaObject.connectSlotsByName(NewWallet)
        NewWallet.setTabOrder(self.name, self.password)
        NewWallet.setTabOrder(self.password, self.passwordVerify)
        NewWallet.setTabOrder(self.passwordVerify, self.saveButton)
        NewWallet.setTabOrder(self.saveButton, self.cancelButton)

    def retranslateUi(self, NewWallet):
        _translate = QtCore.QCoreApplication.translate
        NewWallet.setWindowTitle(_translate("NewWallet", "New Wallet"))
        self.cancelButton.setText(_translate("NewWallet", "Cancel"))
        self.label_3.setText(_translate("NewWallet", "Name:"))
        self.groupBox.setTitle(_translate("NewWallet", "Encryption"))
        self.label.setText(_translate("NewWallet", "Password:"))
        self.label_2.setText(_translate("NewWallet", "Verify Password:"))
        self.label_5.setText(_translate("NewWallet", "A password is not required, but highly recommended."))
        self.error.setText(_translate("NewWallet", "(error)"))
        self.saveButton.setText(_translate("NewWallet", "Create"))

