# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ag/orbit/gui/qt/cash/confirm.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Confirm(object):
    def setupUi(self, Confirm):
        Confirm.setObjectName("Confirm")
        Confirm.setWindowModality(QtCore.Qt.WindowModal)
        Confirm.resize(551, 408)
        Confirm.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Confirm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancelButton = QtWidgets.QPushButton(Confirm)
        self.cancelButton.setDefault(True)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(Confirm)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(Confirm)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.to = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.to.setFont(font)
        self.to.setObjectName("to")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.to)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.totalSatoshi = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.totalSatoshi.setFont(font)
        self.totalSatoshi.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.totalSatoshi.setObjectName("totalSatoshi")
        self.gridLayout.addWidget(self.totalSatoshi, 4, 2, 1, 1)
        self.amountSatoshi = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.amountSatoshi.setFont(font)
        self.amountSatoshi.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.amountSatoshi.setObjectName("amountSatoshi")
        self.gridLayout.addWidget(self.amountSatoshi, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.feeSatoshi = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.feeSatoshi.setFont(font)
        self.feeSatoshi.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.feeSatoshi.setObjectName("feeSatoshi")
        self.gridLayout.addWidget(self.feeSatoshi, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.amountBCH = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.amountBCH.setFont(font)
        self.amountBCH.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.amountBCH.setObjectName("amountBCH")
        self.gridLayout.addWidget(self.amountBCH, 2, 1, 1, 1)
        self.totalBCH = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.totalBCH.setFont(font)
        self.totalBCH.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.totalBCH.setObjectName("totalBCH")
        self.gridLayout.addWidget(self.totalBCH, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.feeBCH = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.feeBCH.setFont(font)
        self.feeBCH.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.feeBCH.setObjectName("feeBCH")
        self.gridLayout.addWidget(self.feeBCH, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.availableBCH = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.availableBCH.setFont(font)
        self.availableBCH.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.availableBCH.setObjectName("availableBCH")
        self.gridLayout.addWidget(self.availableBCH, 1, 1, 1, 1)
        self.availableSatoshi = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.availableSatoshi.setFont(font)
        self.availableSatoshi.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.availableSatoshi.setObjectName("availableSatoshi")
        self.gridLayout.addWidget(self.availableSatoshi, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.error = QtWidgets.QLabel(Confirm)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.error.setFont(font)
        self.error.setStyleSheet("color:red")
        self.error.setAlignment(QtCore.Qt.AlignCenter)
        self.error.setObjectName("error")
        self.verticalLayout.addWidget(self.error)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.status = QtWidgets.QLabel(Confirm)
        font = QtGui.QFont()
        font.setItalic(True)
        self.status.setFont(font)
        self.status.setObjectName("status")
        self.horizontalLayout_2.addWidget(self.status)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.confirmButton = QtWidgets.QPushButton(Confirm)
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout_2.addWidget(self.confirmButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Confirm)
        QtCore.QMetaObject.connectSlotsByName(Confirm)

    def retranslateUi(self, Confirm):
        _translate = QtCore.QCoreApplication.translate
        Confirm.setWindowTitle(_translate("Confirm", "Confirm Transaction"))
        self.cancelButton.setText(_translate("Confirm", "Cancel"))
        self.label.setText(_translate("Confirm", "Confirm Transaction"))
        self.groupBox.setTitle(_translate("Confirm", "Bitcoin Cash"))
        self.label_2.setText(_translate("Confirm", "To:"))
        self.to.setText(_translate("Confirm", "(address)"))
        self.totalSatoshi.setText(_translate("Confirm", "(total)"))
        self.amountSatoshi.setText(_translate("Confirm", "(amount)"))
        self.label_7.setText(_translate("Confirm", "Satoshi"))
        self.feeSatoshi.setText(_translate("Confirm", "(fee)"))
        self.label_3.setText(_translate("Confirm", "- Sending"))
        self.label_5.setText(_translate("Confirm", "= Total:"))
        self.amountBCH.setText(_translate("Confirm", "(amount)"))
        self.totalBCH.setText(_translate("Confirm", "(total)"))
        self.label_6.setText(_translate("Confirm", "BCH"))
        self.feeBCH.setText(_translate("Confirm", "(fee)"))
        self.label_4.setText(_translate("Confirm", "- Fee:"))
        self.label_8.setText(_translate("Confirm", "Available:"))
        self.availableBCH.setText(_translate("Confirm", "(available)"))
        self.availableSatoshi.setText(_translate("Confirm", "(available)"))
        self.error.setText(_translate("Confirm", "(error)"))
        self.status.setText(_translate("Confirm", "(status)"))
        self.confirmButton.setText(_translate("Confirm", "Broadcast"))

