# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ag/orbit/gui/qt/main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(633, 577)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Main.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(24, 24))
        self.label_5.setMaximumSize(QtCore.QSize(24, 24))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icons/logo.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.wallets = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wallets.sizePolicy().hasHeightForWidth())
        self.wallets.setSizePolicy(sizePolicy)
        self.wallets.setObjectName("wallets")
        self.horizontalLayout.addWidget(self.wallets)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.main = QtWidgets.QStackedWidget(self.centralwidget)
        self.main.setObjectName("main")
        self.splash = QtWidgets.QWidget()
        self.splash.setObjectName("splash")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.splash)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.splash)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.splash)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/images/logo.png"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.splash)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.main.addWidget(self.splash)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.page_2)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.main.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.main)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.error = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.error.setFont(font)
        self.error.setStyleSheet("color: red")
        self.error.setAlignment(QtCore.Qt.AlignCenter)
        self.error.setObjectName("error")
        self.verticalLayout.addWidget(self.error)
        Main.setCentralWidget(self.centralwidget)
        self.menu = QtWidgets.QMenuBar(Main)
        self.menu.setGeometry(QtCore.QRect(0, 0, 633, 36))
        self.menu.setObjectName("menu")
        self.menuFile = QtWidgets.QMenu(self.menu)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menu)
        self.menuHelp.setObjectName("menuHelp")
        self.menuWallet = QtWidgets.QMenu(self.menu)
        self.menuWallet.setObjectName("menuWallet")
        Main.setMenuBar(self.menu)
        self.status = QtWidgets.QStatusBar(Main)
        self.status.setObjectName("status")
        Main.setStatusBar(self.status)
        self.actionQuit = QtWidgets.QAction(Main)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon1)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(Main)
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName("actionAbout")
        self.actionNew = QtWidgets.QAction(Main)
        self.actionNew.setObjectName("actionNew")
        self.actionImport = QtWidgets.QAction(Main)
        self.actionImport.setObjectName("actionImport")
        self.actionRename = QtWidgets.QAction(Main)
        self.actionRename.setObjectName("actionRename")
        self.actionShow_Key = QtWidgets.QAction(Main)
        self.actionShow_Key.setObjectName("actionShow_Key")
        self.actionRemove = QtWidgets.QAction(Main)
        self.actionRemove.setObjectName("actionRemove")
        self.actionClose = QtWidgets.QAction(Main)
        self.actionClose.setObjectName("actionClose")
        self.actionSet_Password = QtWidgets.QAction(Main)
        self.actionSet_Password.setObjectName("actionSet_Password")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuWallet.addAction(self.actionNew)
        self.menuWallet.addAction(self.actionImport)
        self.menuWallet.addSeparator()
        self.menuWallet.addAction(self.actionRename)
        self.menuWallet.addAction(self.actionSet_Password)
        self.menuWallet.addAction(self.actionClose)
        self.menuWallet.addSeparator()
        self.menuWallet.addAction(self.actionShow_Key)
        self.menuWallet.addSeparator()
        self.menuWallet.addAction(self.actionRemove)
        self.menu.addAction(self.menuFile.menuAction())
        self.menu.addAction(self.menuWallet.menuAction())
        self.menu.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Main)
        self.main.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.actionQuit.triggered.connect(Main.close)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "ORBIT Wallet"))
        self.label_3.setText(_translate("Main", "Wallet:"))
        self.label_4.setText(_translate("Main", "ORBIT Bitcoin Cash"))
        self.label.setText(_translate("Main", "Open a wallet to begin"))
        self.label_6.setText(_translate("Main", "Bitcoin Cash"))
        self.pushButton.setText(_translate("Main", "Receive..."))
        self.pushButton_2.setText(_translate("Main", "Transfer..."))
        self.pushButton_3.setText(_translate("Main", "Send..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Main", "Cash"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Main", "Tokens"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Main", "Crowd Sales"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Main", "Free Faucets"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Main", "Admin"))
        self.error.setText(_translate("Main", "(error)"))
        self.menuFile.setTitle(_translate("Main", "&File"))
        self.menuHelp.setTitle(_translate("Main", "&Help"))
        self.menuWallet.setTitle(_translate("Main", "&Wallet"))
        self.actionQuit.setText(_translate("Main", "&Quit"))
        self.actionQuit.setShortcut(_translate("Main", "Alt+F4"))
        self.actionAbout.setText(_translate("Main", "&About"))
        self.actionNew.setText(_translate("Main", "&New..."))
        self.actionImport.setText(_translate("Main", "&Import..."))
        self.actionRename.setText(_translate("Main", "&Rename..."))
        self.actionShow_Key.setText(_translate("Main", "Show &Private Key"))
        self.actionRemove.setText(_translate("Main", "&Delete..."))
        self.actionClose.setText(_translate("Main", "&Close"))
        self.actionSet_Password.setText(_translate("Main", "&Set Password..."))

from . import icons_rc
from . import images_rc
