# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ag/orbit/gui/qt/main.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(467, 548)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Main.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(24, 24))
        self.label_5.setMaximumSize(QtCore.QSize(24, 24))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icons/logo.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.wallets = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wallets.sizePolicy().hasHeightForWidth())
        self.wallets.setSizePolicy(sizePolicy)
        self.wallets.setObjectName("wallets")
        self.horizontalLayout.addWidget(self.wallets)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splash = QtWidgets.QWidget(self.centralwidget)
        self.splash.setObjectName("splash")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.splash)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.splash)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.splash)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/images/logo.png"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.splash)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.splash)
        Main.setCentralWidget(self.centralwidget)
        self.menu = QtWidgets.QMenuBar(Main)
        self.menu.setGeometry(QtCore.QRect(0, 0, 467, 22))
        self.menu.setObjectName("menu")
        self.menuFile = QtWidgets.QMenu(self.menu)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menu)
        self.menuHelp.setObjectName("menuHelp")
        self.menuWallet = QtWidgets.QMenu(self.menu)
        self.menuWallet.setObjectName("menuWallet")
        Main.setMenuBar(self.menu)
        self.status = QtWidgets.QStatusBar(Main)
        self.status.setObjectName("status")
        Main.setStatusBar(self.status)
        self.actionQuit = QtWidgets.QAction(Main)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon1)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(Main)
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName("actionAbout")
        self.actionNew = QtWidgets.QAction(Main)
        self.actionNew.setObjectName("actionNew")
        self.actionImport = QtWidgets.QAction(Main)
        self.actionImport.setObjectName("actionImport")
        self.actionRename = QtWidgets.QAction(Main)
        self.actionRename.setObjectName("actionRename")
        self.actionShow_Key = QtWidgets.QAction(Main)
        self.actionShow_Key.setObjectName("actionShow_Key")
        self.actionRemove = QtWidgets.QAction(Main)
        self.actionRemove.setObjectName("actionRemove")
        self.actionClose = QtWidgets.QAction(Main)
        self.actionClose.setObjectName("actionClose")
        self.actionSet_Password = QtWidgets.QAction(Main)
        self.actionSet_Password.setObjectName("actionSet_Password")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuWallet.addAction(self.actionNew)
        self.menuWallet.addAction(self.actionImport)
        self.menuWallet.addSeparator()
        self.menuWallet.addAction(self.actionRename)
        self.menuWallet.addAction(self.actionSet_Password)
        self.menuWallet.addAction(self.actionClose)
        self.menuWallet.addSeparator()
        self.menuWallet.addAction(self.actionShow_Key)
        self.menuWallet.addSeparator()
        self.menuWallet.addAction(self.actionRemove)
        self.menu.addAction(self.menuFile.menuAction())
        self.menu.addAction(self.menuWallet.menuAction())
        self.menu.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Main)
        self.actionQuit.triggered.connect(Main.close)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "ORBIT Wallet"))
        self.label_3.setText(_translate("Main", "Wallet:"))
        self.label_4.setText(_translate("Main", "ORBIT Bitcoin Cash"))
        self.label.setText(_translate("Main", "Open a wallet to begin"))
        self.menuFile.setTitle(_translate("Main", "File"))
        self.menuHelp.setTitle(_translate("Main", "Help"))
        self.menuWallet.setTitle(_translate("Main", "Wallet"))
        self.actionQuit.setText(_translate("Main", "Quit"))
        self.actionQuit.setShortcut(_translate("Main", "Alt+F4"))
        self.actionAbout.setText(_translate("Main", "About"))
        self.actionNew.setText(_translate("Main", "New..."))
        self.actionImport.setText(_translate("Main", "Import..."))
        self.actionRename.setText(_translate("Main", "Rename..."))
        self.actionShow_Key.setText(_translate("Main", "Show Private Key"))
        self.actionRemove.setText(_translate("Main", "Delete..."))
        self.actionClose.setText(_translate("Main", "Close"))
        self.actionSet_Password.setText(_translate("Main", "Set Password..."))

from . import icons_rc
from . import images_rc
